version: 2

workflows:
  version: 2
  pipeline:
    jobs:
    - 0-unit-py36
    - 0-rpm-centos7


jobs:
  0-unit-py36:
    docker: [{image: "dalibo/cornac-sdk:centos7"}]
    environment:
      XDG_CACHE_HOME: /workspace/.cache/
    working_directory: /workspace
    steps:
    - checkout
    - restore_cache:
        key: v1-cornac-unit
    - run:
        name: Install requirements
        command: |
          cd service/;
          poetry install;
    - save_cache:
        key: v1-cornac-unit-{{ epoch }}
        paths: ["~/workspace/.cache/"]
    - run:
        name: Python tests
        command: |
          cd service/;
          poetry run flake8 cornac/ tests/;
          poetry run pytest -x tests/unit/;

  0-rpm-centos7:
    docker: [{image: "dalibo/cornac-sdk:centos7"}]
    environment:
      XDG_CACHE_HOME: /workspace/.cache/
    working_directory: /workspace
    steps:
    - checkout
    - restore_cache:
        key: v1-cornac-unit
    - run:
        name: Build Python packages
        command: |
          cd service/;
          poetry -vvv build
    - run:
        name: Build rpm package from wheel
        command: |
          cd service/;
          packaging/mkrpm dist/pgCornac-*.whl
    - save_cache:
        key: v1-cornac-unit-{{ epoch }}
        paths: ["/workspace/.cache/"]
