version: 2

workflows:
  version: 2
  pipeline:
    jobs:
    - 0-lint-py37

jobs:
  0-lint-py37:
    docker: [{image: "python:3.7-slim"}]
    working_directory: ~/workspace
    steps:
    - checkout
    - restore_cache:
        keys: [cornac-unit]
    - run:
        name: Install requirements
        command: |
          # Create a cacheable venv/
          python -m venv .venv/
          . .venv/bin/activate
          pip install --upgrade -r service/requirements-dev.txt -e service/
          pip check
    - save_cache:
        key: cornac-unit-{{ epoch }}
        paths:
        - /root/.cache/pip
        - "~/.cache/pip/"
        - ".venv"
    - run:
        name: Python tests
        command: |
          . .venv/bin/activate
          flake8 service/
